dist: bionic
language: python
python:
 - "3.6"
cache: pip
before_install:
 - sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
 - sudo apt update 
 - sudo apt-get install kicad kicad-symbols kicad-templates kicad-footprints kicad-packages3d
install:
 - pip install skidl
script: 
 - python KiCAD_skidl_travis.py
