language: python
python:
 - "3.6"
cache: pip
before_install:
 - sudo apt-get install kicad kicad-symbols kicad-templates kicad-footprints kicad-packages3d
install:
 - pip install skidl
script: 
 - python KiCAD_skidl_travis.py
